# Generated by Django 3.0.2 on 2020-01-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20200113_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='creation_date',
        ),
    ]
