# Generated by Django 3.0.2 on 2020-02-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20200125_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='difficulte',
            field=models.CharField(choices=[('FA', 'facile'), ('MO', 'moyenne'), ('DI', 'difficile')], default='MO', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='satisfaction',
            field=models.CharField(choices=[('PS', 'Pas Satisfait'), ('SA', 'Satisfait'), ('TS', 'Très Satisfait')], default='SA', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='total_time',
            field=models.FloatField(default='1'),
        ),
    ]
