# Generated by Django 3.0.2 on 2020-01-21 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('difficulte', models.CharField(choices=[('FA', 'facile'), ('MO', 'moyenne'), ('DI', 'difficile')], default='MO', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('dateDebut', models.DateField(auto_now_add=True)),
                ('dateFin', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
