# Generated by Django 3.0.2 on 2020-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
