# Generated by Django 3.0.1 on 2020-01-05 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('type', models.CharField(default='default_type', max_length=80)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('difficulte', models.CharField(choices=[('FA', 'facile'), ('MO', 'moyenne'), ('DI', 'difficile')], default='MO', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
