# Generated by Django 3.0.1 on 2020-01-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Matiere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='content_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
