# Generated by Django 3.0.1 on 2020-01-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matiere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
