# Generated by Django 3.0.1 on 2020-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matiere', '0002_matiere_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
