# Generated by Django 3.0.1 on 2020-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matiere', '0003_auto_20200105_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
