# Generated by Django 3.0.2 on 2020-01-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Semestre', '0002_auto_20200121_0947'),
        ('Matiere', '0006_auto_20200121_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Semestre.Semestre'),
        ),
    ]
