# Generated by Django 3.0.2 on 2020-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matiere', '0007_matiere_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='type',
            field=models.CharField(choices=[('LI', 'Littérature'), ('MA', 'Mathématiques'), ('PH', 'Physique'), ('BI', 'Biologie'), ('HI', 'Histoire'), ('LA', 'Langue')], default='MA', max_length=30),
        ),
    ]
