export const GET_NOTES = "GET_NOTES";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE";
export const ADD_NOTE_STARTED = "ADD_NOTE_STARTED"
export const GET_ALL_MATIERE = "GET_ALL_MATIERE";
export const ADD_MATIERE_STARTED = "ADD_MATIERE_STARTED";
export const ADD_MATIERE_SUCCESS = "ADD_MATIERE_SUCCESS";
export const ADD_MATIERE_FAILURE = "ADD_MATIERE_FAILURE";
